FROM node:lts-alpine3.17 as build

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY ./services/webapp/*.json .

RUN npm install

COPY ./services/webapp/src/client ./src/client

# Build the client for production
RUN npm run build:client

FROM nginx:latest as server

EXPOSE 3000

COPY ./docker/dockerfiles/webapp-client/client.prod.nginx.conf /etc/nginx/nginx.conf

COPY --from=build /app/dist /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]